// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptHostKey(arg1, arg2) {
  return window['go']['main']['App']['AcceptHostKey'](arg1, arg2);
}

export function CheckPorts(arg1, arg2) {
  return window['go']['main']['App']['CheckPorts'](arg1, arg2);
}

export function CleanupSelectedFootprint(arg1, arg2, arg3) {
  return window['go']['main']['App']['CleanupSelectedFootprint'](arg1, arg2, arg3);
}

export function DeleteCostVPSInstance(arg1) {
  return window['go']['main']['App']['DeleteCostVPSInstance'](arg1);
}

export function GetCostV2Instances() {
  return window['go']['main']['App']['GetCostV2Instances']();
}

export function GetCostV2Summary() {
  return window['go']['main']['App']['GetCostV2Summary']();
}

export function InspectVPS(arg1) {
  return window['go']['main']['App']['InspectVPS'](arg1);
}

export function LinkVPSProfile(arg1, arg2) {
  return window['go']['main']['App']['LinkVPSProfile'](arg1, arg2);
}

export function LoadAppState() {
  return window['go']['main']['App']['LoadAppState']();
}

export function MeasureLatency(arg1, arg2) {
  return window['go']['main']['App']['MeasureLatency'](arg1, arg2);
}

export function RunIPQuality(arg1) {
  return window['go']['main']['App']['RunIPQuality'](arg1);
}

export function RunNodeSpeedTest(arg1, arg2) {
  return window['go']['main']['App']['RunNodeSpeedTest'](arg1, arg2);
}

export function RunSpeedTest(arg1) {
  return window['go']['main']['App']['RunSpeedTest'](arg1);
}

export function SaveAppState(arg1) {
  return window['go']['main']['App']['SaveAppState'](arg1);
}

export function SaveCostVPSInstance(arg1) {
  return window['go']['main']['App']['SaveCostVPSInstance'](arg1);
}

export function ScanFootprint(arg1) {
  return window['go']['main']['App']['ScanFootprint'](arg1);
}

export function StartDeploy(arg1, arg2) {
  return window['go']['main']['App']['StartDeploy'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UninstallStarter(arg1, arg2) {
  return window['go']['main']['App']['UninstallStarter'](arg1, arg2);
}
