// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPorts(arg1:main.SSHProfile,arg2:Array<number>):Promise<Record<string, any>>;

export function CleanupSelectedFootprint(arg1:main.SSHProfile,arg2:Array<string>,arg3:boolean):Promise<Record<string, any>>;

export function InspectVPS(arg1:main.SSHProfile):Promise<Record<string, any>>;

export function LoadAppState():Promise<Record<string, any>>;

export function MeasureLatency(arg1:main.SSHProfile,arg2:main.DeployConfig):Promise<Record<string, any>>;

export function RunIPQuality(arg1:main.SSHProfile):Promise<Record<string, any>>;

export function RunNodeSpeedTest(arg1:main.SSHProfile,arg2:main.DeployConfig):Promise<Record<string, any>>;

export function RunSpeedTest(arg1:main.SSHProfile):Promise<Record<string, any>>;

export function SaveAppState(arg1:main.AppState):Promise<Record<string, any>>;

export function ScanFootprint(arg1:main.SSHProfile):Promise<Record<string, any>>;

export function StartDeploy(arg1:main.SSHProfile,arg2:main.DeployConfig):Promise<Record<string, any>>;

export function TestConnection(arg1:main.SSHProfile):Promise<Record<string, any>>;

export function UninstallStarter(arg1:main.SSHProfile,arg2:boolean):Promise<Record<string, any>>;
