// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {cost} from '../models';

export function AcceptHostKey(arg1:string,arg2:number):Promise<void>;

export function CheckPorts(arg1:config.SSHProfile,arg2:Array<number>):Promise<Record<string, any>>;

export function CleanupSelectedFootprint(arg1:config.SSHProfile,arg2:Array<string>,arg3:boolean):Promise<Record<string, any>>;

export function DeleteCostVPSInstance(arg1:string):Promise<Record<string, any>>;

export function GetCostV2Instances():Promise<Record<string, any>>;

export function GetCostV2Summary():Promise<Record<string, any>>;

export function InspectVPS(arg1:config.SSHProfile):Promise<Record<string, any>>;

export function LinkVPSProfile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function LoadAppState():Promise<Record<string, any>>;

export function MeasureLatency(arg1:config.SSHProfile,arg2:config.DeployConfig):Promise<Record<string, any>>;

export function RunIPQuality(arg1:config.SSHProfile):Promise<Record<string, any>>;

export function RunNodeSpeedTest(arg1:config.SSHProfile,arg2:config.DeployConfig):Promise<Record<string, any>>;

export function RunSpeedTest(arg1:config.SSHProfile):Promise<Record<string, any>>;

export function SaveAppState(arg1:config.AppState):Promise<Record<string, any>>;

export function SaveCostVPSInstance(arg1:cost.VPSInstance):Promise<Record<string, any>>;

export function ScanFootprint(arg1:config.SSHProfile):Promise<Record<string, any>>;

export function StartDeploy(arg1:config.SSHProfile,arg2:config.DeployConfig):Promise<Record<string, any>>;

export function TestConnection(arg1:config.SSHProfile):Promise<Record<string, any>>;

export function UninstallStarter(arg1:config.SSHProfile,arg2:boolean):Promise<Record<string, any>>;
